columnSuffix: null
contentColumnType: string
fieldGroup: eae6388b-45fe-4218-a084-a97310884eef # Common
handle: pageBlocks
instructions: null
name: 'Page Blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pageblocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
